# Generated by Django 4.1.2 on 2022-10-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='bank_tran_id',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='base_fair',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='card_brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='card_issuer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='card_issuer_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='card_issuer_country_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='card_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='card_sub_brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='currency',
            field=models.CharField(default='BDT', max_length=10),
        ),
        migrations.AddField(
            model_name='transactions',
            name='currency_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='response_of_failed',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='response_of_val',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='risk_title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='store_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='val_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='card_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
